"""empty message

Revision ID: 27fe451e9857
Revises: 4b74475a768c
Create Date: 2018-12-29 14:13:34.563943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fe451e9857'
down_revision = '4b74475a768c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_granted_ticket', sa.Column('validate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_granted_ticket', 'validate')
    # ### end Alembic commands ###
