"""empty message

Revision ID: 4b74475a768c
Revises: 545d88d0f366
Create Date: 2018-12-29 11:24:37.531293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b74475a768c'
down_revision = '545d88d0f366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('logout_url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'logout_url')
    # ### end Alembic commands ###
