"""empty message

Revision ID: 545d88d0f366
Revises: 95959c778b16
Create Date: 2018-12-29 10:39:58.940671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545d88d0f366'
down_revision = '95959c778b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ticket', sa.Column('tgt_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_ticket', 'tgt_id')
    # ### end Alembic commands ###
