"""empty message

Revision ID: 95959c778b16
Revises: 1dda1369dea4
Create Date: 2018-12-28 15:34:44.477291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95959c778b16'
down_revision = '1dda1369dea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ticket', sa.Column('service_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_ticket', 'service_id')
    # ### end Alembic commands ###
