"""empty message

Revision ID: afb1d122d50c
Revises: 27fe451e9857
Create Date: 2018-12-29 14:49:28.240095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb1d122d50c'
down_revision = '27fe451e9857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ticket', sa.Column('validate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_ticket', 'validate')
    # ### end Alembic commands ###
