"""empty message

Revision ID: fd58aef7b183
Revises: 78cae6318132
Create Date: 2018-12-28 11:30:22.952745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd58aef7b183'
down_revision = '78cae6318132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ticket', sa.Column('expires_in', sa.BigInteger(), nullable=True))
    op.add_column('ticket_granted_ticket', sa.Column('expires_in', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_granted_ticket', 'expires_in')
    op.drop_column('service_ticket', 'expires_in')
    # ### end Alembic commands ###
